import Head from "next/head";
import Carousal from "../components/home/Carousal";
import Hero from "../components/home/Hero";
import Stats from "../components/home/Stats";
import Testimonials from "../components/home/Testimonials";
import Navbar from "../components/common/Navbar";
import Footer from "../components/common/Footer";
import CoreTeam from "../components/home/CoreTeam";
import Donate from "../components/home/Donate";
import About from "../components/home/About";
import Project from "../components/home/Project";
import { useEffect } from 'react';
import Link from 'next/link';
import FAQPage from "../components/home/FAQPage";
import Collaborations from "../components/home/Collaborations.js";
// import FeaturedIn from "../components/home/FeaturedIn";
import YouTubeEmbed from "../components/home/YoutubeEmbed";
// import FeedbackForm from "../components/home/FeedbackForm";

export default function Home() {

  useEffect(() => {
    const handleScroll = () => {
      localStorage.setItem('scrollPosition', window.pageYOffset.toString());
    };

    window.addEventListener('scroll', handleScroll);

    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Sampoorna Foundation</title>
        {/* Meta Tags Dynamically generated by metaseo.itsvg.in */}
        <meta name="title" content="Sampoorna Foundation" />
        <meta
          name="description"
          content="Sampoorna foundation provides overall development to underprivileged children through quality teaching and extra- curricular activities"
        />

        <meta property="og:type" content="website" />
        <meta property="og:url" content="teamhnm.org" />
        <meta property="og:title" content="Sampoorna Foundation" />
        <meta
          property="og:description"
          content="Sampoorna foundation provides overall development to underprivileged children through quality teaching and extra- curricular activities"
        />
        <meta property="twitter:title" content="Sampoorna Foundation" />
        <meta
          property="twitter:description"
          content="Sampoorna foundation provides overall development to underprivileged children through quality teaching and extra- curricular activities"
        />
      </Head>

      <main className="">
        <Navbar />
        <Hero />
        <YouTubeEmbed />
        {/* <Carousal /> */}
        <Link href="/project">
          <Project />
        </Link>
        <Stats />
        <Donate />
        <CoreTeam />
        <Collaborations />
        {/* <FeaturedIn/> */}
        <Testimonials />
        <About />
        <FAQPage />

        {/* <FeedbackForm /> */}

      </main>

      <Footer />
    </>
  );
}
