import Head from "next/head";
import Carousal from "../components/home/Carousal";
import Hero from "../components/home/Hero";
import Stats from "../components/home/Stats";
import Testimonials from "../components/home/Testimonials";
import Navbar from "../components/common/Navbar";
import Footer from "../components/common/Footer";
import CoreTeam from "../components/home/CoreTeam";
import Donate from "../components/home/Donate";
import About from "../components/home/About";
import Project from "../components/home/Project";
import { useEffect } from 'react';
import Link from 'next/link';

export default function Home() {

  useEffect(() => {
    const handleScroll = () => {
      localStorage.setItem('scrollPosition', window.pageYOffset.toString());
    };

    window.addEventListener('scroll', handleScroll);

    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Sampoorna Foundation</title>
        {/* Meta Tags Dynamically generated by metaseo.itsvg.in */}
        <meta name="title" content="Sampoorna Foundation" />
        <meta
          name="description"
          content="Sampoorna foundation provides overall development to underprivileged children through quality teaching and extra- curricular activities"
        />
        <meta name="copyright" content="VishwaGauravIn" />

        <meta property="og:type" content="website" />
        <meta property="og:url" content="teamhnm.org" />
        <meta property="og:title" content="Sampoorna Foundation" />
        <meta
          property="og:description"
          content="Sampoorna foundation provides overall development to underprivileged children through quality teaching and extra- curricular activities"
        />
        {/* <meta property="og:image" content="https://teamhnm.org/og.png" /> */}
        {/* <meta property="twitter:card" content="summary_large_image" /> */}
        {/* <meta property="twitter:url" content="teamhnm.org" /> */}
        <meta property="twitter:title" content="Sampoorna Foundation" />
        <meta
          property="twitter:description"
          content="Sampoorna foundation provides overall development to underprivileged children through quality teaching and extra- curricular activities"
        />
        <meta property="twitter:image" content="https://teamhnm.org/og.png" />
      </Head>

      <main className="">
        <Navbar />
        <Hero />
        <Carousal />
        <Link href="/project">
          <Project />
        </Link>
        <Stats />
        <Donate />
        <CoreTeam />
        <About />
        <Testimonials />
      </main>

      <Footer />
    </>
  );
}
